/*
 * Single source of truth for field definitions across all 6 sections.
 * Used by: forms, records table, edit modal, CSV import/export.
 */

export const FIELD_SCHEMA = {
  product: [
    { name: 'SKU', label: 'SKU', type: 'text' },
    { name: 'Barcode', label: 'Barcode', type: 'text' },
    { name: 'Brand1', label: 'Brand', type: 'text' },
    { name: 'Category', label: 'Category', type: 'text' },
    { name: 'Sub_Category', label: 'Sub-category', type: 'text' },
    { name: 'Product_Name', label: 'Product Name', type: 'text' },
    { name: 'Model_Number', label: 'Model Number', type: 'text' },
    { name: 'Series', label: 'Series / Generation', type: 'text' },
    { name: 'Color', label: 'Color', type: 'text' },
    { name: 'Storage_RAM', label: 'Storage / RAM', type: 'text' },
    { name: 'Processor', label: 'Processor', type: 'text' },
    { name: 'Screen_Size', label: 'Screen Size', type: 'text' },
    { name: 'Keyboard_Layout', label: 'Keyboard Layout', type: 'text' },
    { name: 'OS', label: 'OS', type: 'text' },
    { name: 'Product_Type', label: 'Product Type', type: 'text', options: ['New', 'Refurbished', 'Open Box', 'Used', 'Parts Only'] },
  ],

  device: [
    { name: 'IMEI_1', label: 'IMEI 1', type: 'text' },
    { name: 'IMEI_2', label: 'IMEI 2 / eSIM', type: 'text' },
    { name: 'Serial_Number', label: 'Serial Number', type: 'text' },
    { name: 'Service_Tag', label: 'Service Tag', type: 'text' },
    { name: 'Battery_Serial', label: 'Battery Serial', type: 'text' },
    { name: 'Asset_Tag', label: 'Asset Tag', type: 'text' },
    { name: 'Vendor_Lot_Number', label: 'Vendor Lot No.', type: 'text' },
    { name: 'Data_Wipe_Cert_ID', label: 'Data Wipe Cert ID', type: 'text' },
    { name: 'Diagnostic_Report_ID', label: 'Diagnostic Report ID', type: 'text' },
    { name: 'Grade_ID', label: 'Grade ID', type: 'text' },
    { name: 'QC_Engineer_Name', label: 'QC Engineer', type: 'text' },
    { name: 'QC_Date', label: 'QC Date', type: 'date' },
    { name: 'Laptop_Serial', label: 'Laptop Serial', type: 'text' },
    { name: 'Laptop_Service_Tag', label: 'Laptop Service Tag', type: 'text' },
    { name: 'Battery_Cyle_Count', label: 'Battery Cycles', type: 'number' },
    { name: 'SSD_Health', label: 'SSD Health %', type: 'text' },
    { name: 'Keyboard_Type', label: 'Keyboard Type', type: 'text' },
  ],

  inventory: [
    { name: 'Current_Stock', label: 'Current Stock', type: 'number' },
    { name: 'Available_Stock', label: 'Available Stock', type: 'number' },
    { name: 'Reserved_Stock', label: 'Reserved Stock', type: 'number' },
    { name: 'In_Transit_Stock', label: 'In Transit', type: 'number' },
    { name: 'Repair_Stock', label: 'Repair Stock', type: 'number' },
    { name: 'Dead_Stock', label: 'Dead Stock', type: 'number' },
    { name: 'Returned_Stock', label: 'Returned Stock', type: 'number' },
    { name: 'Damaged_Stock', label: 'Damaged Stock', type: 'number' },
    { name: 'RMA_Stock', label: 'RMA Stock', type: 'number' },
    { name: 'Warehouse_Location', label: 'Warehouse', type: 'text' },
    { name: 'Bin_Rack_Shelf', label: 'Bin / Rack / Shelf', type: 'text' },
    { name: 'Country_Warehouse', label: 'Country Warehouse', type: 'text' },
    { name: 'Supplier_Warehouse', label: 'Supplier Warehouse', type: 'text' },
    { name: 'Stock_Aging_Days', label: 'Stock Aging (days)', type: 'number' },
    { name: 'Last_Inward_Date', label: 'Last Inward Date', type: 'date' },
    { name: 'Last_Outward_Date', label: 'Last Outward Date', type: 'date' },
    { name: 'Reorder_Point', label: 'Reorder Point', type: 'number' },
    { name: 'Minimum_Stock', label: 'Min Stock', type: 'number' },
    { name: 'Maximum_Stock', label: 'Max Stock', type: 'number' },
    { name: 'Lead_Time', label: 'Lead Time (days)', type: 'number' },
    { name: 'Safety_Stock', label: 'Safety Stock', type: 'number' },
  ],

  pricing: [
    { name: 'Vendor_Buy_Price', label: 'Buy Price', type: 'number' },
    { name: 'Landed_Cost', label: 'Landed Cost', type: 'number' },
    { name: 'Import_Duty', label: 'Import Duty', type: 'number' },
    { name: 'VAT_Input', label: 'VAT Input', type: 'number' },
    { name: 'Repair_Cost', label: 'Repair Cost', type: 'number' },
    { name: 'Accessory_Cost', label: 'Accessory Cost', type: 'number' },
    { name: 'Packaging_Cost', label: 'Packaging Cost', type: 'number' },
    { name: 'QC_Cost', label: 'QC Cost', type: 'number' },
    { name: 'Logistic_Inward', label: 'Logistics Inward', type: 'number' },
    { name: 'Refurbishment_Cost1', label: 'Refurb Cost', type: 'number' },
    { name: 'Total_Cost_Price', label: 'Total Cost', type: 'number' },
    { name: 'MRP', label: 'MRP', type: 'number' },
    { name: 'Retail_Selling_Price', label: 'Retail Price', type: 'number' },
    { name: 'Wholesale_Price', label: 'Wholesale', type: 'number' },
    { name: 'B2B_Bulk_Price', label: 'B2B Bulk', type: 'number' },
    { name: 'Price_Amazon', label: 'Amazon Price', type: 'number' },
    { name: 'Price_Noon', label: 'Noon Price', type: 'number' },
    { name: 'Website_Price', label: 'Website Price', type: 'number' },
    { name: 'POS_Store_Price', label: 'POS Price', type: 'number' },
    { name: 'Offer_Price', label: 'Offer Price', type: 'number' },
    { name: 'Coupon_Allowed', label: 'Coupon', type: 'text', options: ['Yes', 'No'] },
    { name: 'Min_Selling_Price', label: 'Min Sell Price', type: 'number' },
    { name: 'MAP_Price', label: 'MAP Price', type: 'number' },
    { name: 'Dealer_Price', label: 'Dealer Price', type: 'number' },
    { name: 'Distributor_Price', label: 'Distributor', type: 'number' },
    { name: 'Gross_Margin', label: 'Gross %', type: 'number' },
    { name: 'Net_Margin', label: 'Net %', type: 'number' },
    { name: 'Contribution_Margin', label: 'Contrib Margin', type: 'number' },
    { name: 'Breakeven_Price', label: 'Breakeven', type: 'number' },
    { name: 'Expected_Profit', label: 'Exp. Profit', type: 'number' },
    { name: 'Realised_Profit', label: 'Real. Profit', type: 'number' },
  ],

  refurbishment: [
    { name: 'Cosmetic_Grade', label: 'Cosmetic Grade', type: 'text', options: ['A+', 'A', 'B', 'C'] },
    { name: 'Functional_Grade', label: 'Functional Grade', type: 'text', options: ['A+', 'A', 'B', 'C'] },
    { name: 'Battery_Health', label: 'Battery %', type: 'number' },
    { name: 'LCD_Condition', label: 'LCD Condition', type: 'text', options: ['Excellent', 'Good', 'Fair', 'Poor', 'Dead'] },
    { name: 'Body_Scratches', label: 'Scratches', type: 'text', options: ['None', 'Minor', 'Moderate', 'Heavy'] },
    { name: 'Keyboard_Condition', label: 'Keyboard', type: 'text', options: ['Excellent', 'Good', 'Fair', 'Poor', 'Dead'] },
    { name: 'Touch_Status', label: 'Touch', type: 'text', options: ['Pass', 'Fail'] },
    { name: 'Speaker_Status', label: 'Speaker', type: 'text', options: ['Pass', 'Fail'] },
    { name: 'Mic_Status', label: 'Mic', type: 'text', options: ['Pass', 'Fail'] },
    { name: 'Camera_Status', label: 'Camera', type: 'text', options: ['Pass', 'Fail'] },
    { name: 'Face_Touch_ID', label: 'Face/Touch ID', type: 'text', options: ['Pass', 'Fail'] },
    { name: 'Ports_Condition', label: 'Ports', type: 'text', options: ['Excellent', 'Good', 'Fair', 'Poor', 'Dead'] },
    { name: 'Painted', label: 'Painted', type: 'text', options: ['Painted', 'Yes', 'No'] },
    { name: 'Parts_Changed', label: 'Parts Changed', type: 'textarea' },
    { name: 'OEM_Parts_Used', label: 'OEM Parts', type: 'text', options: ['Yes', 'No'] },
    { name: 'Warranty_Seal', label: 'Warranty Seal', type: 'text', options: ['Intact', 'Broken', 'N/A'] },
    { name: 'QC_Result', label: 'QC Result', type: 'text', options: ['Pass', 'Fail'] },
    { name: 'Final_Refurb_Date', label: 'Refurb Date', type: 'date' },
  ],

  marketplace: [
    { name: 'Amazon_ASIN', label: 'Amazon ASIN', type: 'text' },
    { name: 'Noon_SKU', label: 'Noon SKU', type: 'text' },
    { name: 'Shopify_SKU', label: 'Shopify SKU', type: 'text' },
    { name: 'Dubizzle_ID', label: 'Dubizzle ID', type: 'text' },
    { name: 'OpenSooq_ID', label: 'OpenSooq ID', type: 'text' },
    { name: 'Category_M', label: 'Category Mapping', type: 'text' },
    { name: 'SEO_Title', label: 'SEO Title', type: 'text' },
    { name: 'Short_Title', label: 'Short Title', type: 'text' },
    { name: 'Marketplace_Bullets', label: 'Bullets', type: 'textarea' },
    { name: 'Condition_Note', label: 'Condition Note', type: 'textarea' },
    { name: 'Listing_Image_Folder', label: 'Image Folder', type: 'text' },
    { name: 'Aplus_Content_Folder', label: 'A+ Folder', type: 'text' },
    { name: 'Ad_Priority', label: 'Ad Priority', type: 'text', options: ['High', 'Medium', 'Low', 'None'] },
    { name: 'Top_SKU_Flag', label: 'Top SKU', type: 'text', options: ['Yes', 'No'] },
    { name: 'Exclusive_SKU_Flag', label: 'Exclusive SKU', type: 'text', options: ['Yes', 'No'] },
  ],
};

/* META fields added by Zoho — excluded from CSV export headers & edit forms */
export const ZOHO_META_FIELDS = ['ID', 'Added_Time', 'Modified_Time', 'Added_User', 'Modified_User'];

export const SECTION_LABELS = {
  product: 'Product Master',
  device: 'Device Tracking',
  inventory: 'Inventory & Stock',
  pricing: 'Pricing & Margin',
  refurbishment: 'Refurbishment Grade',
  marketplace: 'Marketplace Channels',
};
